In [2]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv('Dataset .csv')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [5]:
df = df.rename(columns={df.columns[19]: 'Rating'})
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ï¿½ï¿½stanbul,"Kemankeï¿½ï¿½ Karamustafa Paï¿½ï¿½a Mahallesi, RÛ±htÛ±m ...",Karakï¿½_y,"Karakï¿½_y, ï¿½ï¿½stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz Aï¿½ï¿½acÛ±,208,ï¿½ï¿½stanbul,"Koï¿½ï¿½uyolu Mahallesi, Muhittin ï¿½ï¿½stï¿½_ndaï¿½ï¿½ Cadd...",Koï¿½ï¿½uyolu,"Koï¿½ï¿½uyolu, ï¿½ï¿½stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aï¿½ï¿½ï¿½k Kahve,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ï¿½ï¿½stanbul,"Cafeaï¿½ï¿½a Mahallesi, BademaltÛ± Sokak, No 21/B, ...",Moda,"Moda, ï¿½ï¿½stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

# Level 2

# Task 1
 Task: Table Booking and Online Delivery
 Determine the percentage of restaurants that
 offer table booking and online delivery.
 Compare the average ratings of restaurants
 with table booking and those without.
 Analyze the availability of online delivery
 among restaurants with different price ranges

In [6]:
# Calculate the percentage of restaurants that offer table booking
table_booking_yes = df['Has Table booking'].value_counts()['Yes']
table_booking_no = df['Has Table booking'].value_counts()['No']
table_booking_percentage = (table_booking_yes / (table_booking_yes + table_booking_no)) * 100
print(f"Percentage of restaurants that offer table booking: {table_booking_percentage:.2f}%")

# Calculate the percentage of restaurants that offer online delivery
online_delivery_yes = df['Has Online delivery'].value_counts()['Yes']
online_delivery_no = df['Has Online delivery'].value_counts()['No']
online_delivery_percentage = (online_delivery_yes / (online_delivery_yes + online_delivery_no)) * 100
print(f"Percentage of restaurants that offer online delivery: {online_delivery_percentage:.2f}%")

Percentage of restaurants that offer table booking: 12.12%
Percentage of restaurants that offer online delivery: 25.66%

In [7]:
# Calculate the average rating of restaurants with table booking
avg_rating_table_booking = df[df['Has Table booking'] == 'Yes']['Aggregate rating'].mean()
print(f"Average rating of restaurants with table booking: {avg_rating_table_booking:.2f}")

# Calculate the average rating of restaurants without table booking
avg_rating_no_table_booking = df[df['Has Table booking'] == 'No']['Aggregate rating'].mean()
print(f"Average rating of restaurants without table booking: {avg_rating_no_table_booking:.2f}")

Average rating of restaurants with table booking: 3.44
Average rating of restaurants without table booking: 2.56

In [8]:
# Analyze the availability of online delivery among restaurants with different price ranges
price_ranges = ['Low', 'Medium', 'High']
online_delivery_by_price_range = df.groupby('Price range')['Has Online delivery'].value_counts(normalize=True) * 100

In [9]:
print('Has Online delivery availability by price range:')
print(online_delivery_by_price_range)

Has Online delivery availability by price range:
Price range  Has Online delivery
1            No                     84.225923
             Yes                    15.774077
2            No                     58.689367
             Yes                    41.310633
3            No                     70.809659
             Yes                    29.190341
4            No                     90.955631
             Yes                     9.044369
Name: proportion, dtype: float64

In [10]:
# Group by price range and calculate the percentage of restaurants with online delivery
price_ranges = ['Low', 'Medium', 'High']
for price_range in price_ranges:
    online_delivery_yes = df[(df['Price range'] == price_range) & (df['Has Online delivery'] == 'Yes')].shape[0]
    online_delivery_no = df[(df['Price range'] == price_range) & (df['Has Online delivery'] == 'No')].shape[0]
    
    if online_delivery_yes + online_delivery_no == 0:
        print(f"No restaurants found in {price_range} price range.")
    else:
        online_delivery_percentage = (online_delivery_yes / (online_delivery_yes + online_delivery_no)) * 100
        print(f"Percentage of restaurants with online delivery in {price_range} price range: {online_delivery_percentage:.2f}%")

No restaurants found in Low price range.
No restaurants found in Medium price range.
No restaurants found in High price range.

# Task 2
 Task: Price Range Analysis
 Determine the most common price range
 among all the restaurants.
 Calculate the average rating for each price
 range.
 Identify the color that represents the highest
 average rating among different price ranges

In [11]:
    # Determine the most common price range
most_common_price_range = df['Price range'].value_counts().index[0]
print(f"The most common price range is: {most_common_price_range}")

The most common price range is: 1

In [12]:
# Calculate the average rating for each price range
average_ratings = df.groupby('Price range')['Aggregate rating'].mean()
print("Average ratings for each price range:")
print(average_ratings)

Average ratings for each price range:
Price range
1    1.999887
2    2.941054
3    3.683381
4    3.817918
Name: Aggregate rating, dtype: float64

In [13]:
# Identify the color that represents the highest average rating
highest_average_rating = average_ratings.max()
color_map = {1: 'Blue', 2: 'Orange', 3: 'Red', 4: 'Teal'}
highest_average_rating_color = color_map[average_ratings.idxmax()]
print(f'Color that represents the highest average rating: {highest_average_rating_color}')

Color that represents the highest average rating: Teal

# Task 3
 Task: Feature Engineering
 Extract additional features from the existing
 columns, such as the length of the restaurant
 name or address.
 Create new features like "Has Table Booking"
 or "Has Online Delivery" by encoding
 categorical variables

In [14]:
# feature_engineering.py
# Extract additional features
df['Restaurant Name Length'] = df['Restaurant Name'].apply(len)
df['Address Length'] = df['Address'].apply(len)

# Create new features by encoding categorical variables
df['Has Table booking'] = df['Has Table booking'].map({'Yes': 1, 'No': 0})
df['Has Online delivery'] = df['Has Online delivery'].map({'Yes': 1, 'No': 0})

# One-Hot Encoding for categorical variables
categorical_cols = ['Country Code', 'City', 'Cuisines']
for col in categorical_cols:
    one_hot = pd.get_dummies(df[col], prefix=col)
    df = pd.concat([df, one_hot], axis=1)
    df.drop(col, axis=1, inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Columns: 2001 entries, Restaurant ID to Cuisines_World Cuisine, Patisserie, Cafe
dtypes: bool(1981), float64(3), int64(8), object(9)
memory usage: 19.5+ MB

In [16]:
df.describe()

,Restaurant ID,Longitude,Latitude,Average Cost for two,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes,Restaurant Name Length,Address Length
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,64.126574,25.854381,1199.210763,0.121244,0.256622,1.804837,2.666370,156.909748,15.164171,53.536698
std,8.791521e+06,41.467058,11.007935,16121.183073,0.326428,0.436792,0.905609,1.516378,430.169145,6.858392,17.122035
min,5.300000e+01,-157.948486,-41.330428,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000,13.000000
25%,3.019625e+05,77.081343,28.478713,250.000000,0.000000,0.000000,1.000000,2.500000,5.000000,10.000000,41.000000
50%,6.004089e+06,77.191964,28.570469,400.000000,0.000000,0.000000,2.000000,3.200000,31.000000,14.000000,52.000000
75%,1.835229e+07,77.282006,28.642758,700.000000,0.000000,1.000000,2.000000,3.700000,131.000000,19.000000,64.000000
max,1.850065e+07,174.832089,55.976980,800000.000000,1.000000,1.000000,4.000000,4.900000,10934.000000,54.000000,132.000000

# Thanking You